FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

COPY requirements-viewer.txt .
RUN pip install --no-cache-dir -r requirements-viewer.txt

COPY common ./common
COPY viewer ./viewer

EXPOSE 47831

CMD ["python", "-m", "viewer.main"]
